[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.69.0"
moveneter_sdk = { path = "../moveneter_sdk" }
shared = { path = "../shared" }
nix = { version = "0.25.0", features = ["ioctl", "mman"] }

[dev-dependencies]
opencv = "0.69.0"
moveneter_sdk = { path = "../moveneter_sdk" }
shared = { path = "../shared" }
nix = { version = "0.25.0", features = ["ioctl", "mman"] }