[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tflitec = "0.5.1"
shared = { path = "../shared" }
opencv = "0.69.0"
